import { Esc } from './esc';


export const ESCS: Esc[] = [
    {
        "Cmnt": 1, 
        "CompName": "MCGUI - report", 
        "CustLoc": "EMEA", 
        "CustomerName": "eBRC", 
        "Desc": "Backend Capacity Report Completing with Errors - No Statistics", 
        "EnggLoc": "---", 
        "Esc": 28500, 
        "EscAge": 165, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#51.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Brian Nagle", 
        "OwnerEmail": "brian.nagle@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 270, 
        "SrNumber": "05536311,83188978, 07372714", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|7.3.100-233]", 
        "WhiteBoard": "2017-08-04 (EK): one more month has passed.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 62, 
        "CompName": "DPN Server (gsan avmaint avmgr dpnutils)", 
        "CustLoc": "NA", 
        "CustomerName": "PFIZER INC", 
        "Desc": "[FA] Gen4T node keeps rebooting with \"storage system failure\" error", 
        "EnggLoc": "---", 
        "Esc": 28504, 
        "EscAge": 165, 
        "Mod": 36, 
        "NextUpdateActionPlan": "Setting 6 month expiration.\r\nCorresponding SR closed: 04/26/2017 01:21 PM", 
        "NextUpdateDate": "10-23", 
        "OtherAssignee": "", 
        "Owner": "Vu Duong", 
        "OwnerEmail": "vu.duong@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S5", 
        "SrAge": 175, 
        "SrNumber": "84706368", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "FA ; 2017-06-20:(NJ) Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "Oclc Online Computer Library Center", 
        "Desc": "ESX Host as Dynamic Containers changing host-id number in MCDB, when they aren't changing in vCenter. related to esc 26705.", 
        "EnggLoc": "---", 
        "Esc": 28630, 
        "EscAge": 147, 
        "Mod": 1, 
        "NextUpdateActionPlan": "@MC Team: Is the output in Comment#50 helpful?  Is there something which may have not been done correctly?", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Peter Wright", 
        "OwnerEmail": "peter.wright@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 197, 
        "SrNumber": "06149027", 
        "Team": "SPT", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "2017-07-17 (NJ): either JAR or ESX upgrade resolved the issue; w/t for confirmation; ", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 7, 
        "CompName": "Systems", 
        "CustLoc": "EMEA", 
        "CustomerName": "Repsol - Tres Cantos", 
        "Desc": "Dedicated RMC port is not accessible on Gen4T nodes", 
        "EnggLoc": "---", 
        "Esc": 28670, 
        "EscAge": 144, 
        "Mod": 7, 
        "NextUpdateActionPlan": "- Review logs, wireshark captures.\r\n- Need more accurate network configuration picture of the BMC port, the customer switch port configuration, and the client IP where you run the ping tests.", 
        "NextUpdateDate": "06-23", 
        "OtherAssignee": "", 
        "Owner": "Julio Silva", 
        "OwnerEmail": "alexandre.silva@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 162, 
        "SrNumber": "84952944", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "2017-05-04 (EK): last updt 0419; esc.sev++ wn nec.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Avtar", 
        "CustLoc": "NA", 
        "CustomerName": "Point72, L.P", 
        "Desc": "Exchange DAG backups slow taking more than 11 hrs  verifying Transaction log range", 
        "EnggLoc": "---", 
        "Esc": 29031, 
        "EscAge": 102, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#70", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "Aneesh Gurindapalli", 
        "Owner": "Tahir Mian", 
        "OwnerEmail": "mian_tahir@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 120, 
        "SrNumber": "85754036", 
        "Team": "SPT", 
        "Versions": "[7.4.0-242|7.4.0-242|7.4.100-242]", 
        "WhiteBoard": "2017-07-18 (EK): esc.sev++ wn rdy", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Avtar", 
        "CustLoc": "NA", 
        "CustomerName": "BANK OF AMERICA_SMS MANAGED SERVICES_SANDSTON", 
        "Desc": "WC - Performance - SR<07191686> - SQL Backup reporting 5% change rate, when no new data", 
        "EnggLoc": "---", 
        "Esc": 29082, 
        "EscAge": 95, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "David Templin", 
        "OwnerEmail": "david.templin@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 99, 
        "SrNumber": "07191686", 
        "Team": "SPT", 
        "Versions": "[7.0.0-427|7.0.0-427|7.0.100-427]", 
        "WhiteBoard": "2017-05-22 (EK): wt/(spt+cust) last updt 0706", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "RMAN Module", 
        "CustLoc": "NA", 
        "CustomerName": "Lentech HHS ITO", 
        "Desc": "PR 8585: WC - Oracle - SR 06579289 - random oracle back up failures", 
        "EnggLoc": "---", 
        "Esc": 29149, 
        "EscAge": 85, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Proposed action from Comment#19, and question regarding sufficiency of plan.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Preksha Sisodia", 
        "OwnerEmail": "preksha.sisodia@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 158, 
        "SrNumber": "06579289", 
        "Team": "TicketNWuser", 
        "Versions": "[7.1.1-145|7.1.1-145|7.1.102-21]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "DPN Clients (avtar rman scc web avscan)", 
        "CustLoc": "NA", 
        "CustomerName": "BANCO POPULAR", 
        "Desc": "The 2016-Q4-v2 patch appears to have been installed correctly, but the port scan is still showing issues", 
        "EnggLoc": "---", 
        "Esc": 29160, 
        "EscAge": 84, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Info request", 
        "NextUpdateDate": "07-21", 
        "OtherAssignee": "", 
        "Owner": "Julio Acevedo", 
        "OwnerEmail": "acevedodeleon_julio@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S5", 
        "SrAge": 84, 
        "SrNumber": "07136615", 
        "Team": "SPT", 
        "Versions": "[7.3.0-207|7.3.0-207|7.3.100-233]", 
        "WhiteBoard": "2017-07-04:(AKS) Updated AP", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "Exchange", 
        "CustLoc": "NA", 
        "CustomerName": "Quick Chek Food Stores", 
        "Desc": "Exchange GLR - SR#86414486 - Exchange 2016 CU5 GLR using Itempoint fails to list databases.", 
        "EnggLoc": "---", 
        "Esc": 29181, 
        "EscAge": 82, 
        "Mod": 2, 
        "NextUpdateActionPlan": "- Continue to wait on PM.\r\n  - Waiting on response from Kroll.", 
        "NextUpdateDate": "06-27", 
        "OtherAssignee": "", 
        "Owner": "Russ Logsdon", 
        "OwnerEmail": "russ.logsdon@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 84, 
        "SrNumber": "86414486", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|---|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 7, 
        "CompName": "MCS", 
        "CustLoc": "EMEA", 
        "CustomerName": "AVL LIST GMBH", 
        "Desc": "Many Clients stuck in Waiting-Queued (It flip for RESERVED to AVAILBLe and AVAILABLE to reserve)", 
        "EnggLoc": "---", 
        "Esc": 29195, 
        "EscAge": 77, 
        "Mod": 2, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-28", 
        "OtherAssignee": "", 
        "Owner": "Rej Pervan", 
        "OwnerEmail": "Rej.Pervan@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 182, 
        "SrNumber": "84568508, 86217784", 
        "Team": "TicketNWuser", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "2017-08-02 (EK): Last updt 07/27", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 5, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "DSE GE", 
        "Desc": "Unable to configure LDAP on 2 Avamar Servers", 
        "EnggLoc": "CCOE", 
        "Esc": 29198, 
        "EscAge": 77, 
        "Mod": 5, 
        "NextUpdateActionPlan": "@Support: \r\n  - Comment#20", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Trevor Craig", 
        "OwnerEmail": "craig_trevor@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 103, 
        "SrNumber": "07161311", 
        "Team": "SPT", 
        "Versions": "[7.1.2-21|7.1.2-21|---]", 
        "WhiteBoard": "2017-08-01 (EK): last updt 0627", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "MCGUI", 
        "CustLoc": "EMEA", 
        "CustomerName": "Infineon", 
        "Desc": "MCGUI popup asking user to \"Choose a PKCS11 library\" prior to login screen (7.4.1-58)", 
        "EnggLoc": "---", 
        "Esc": 29223, 
        "EscAge": 75, 
        "Mod": 0, 
        "NextUpdateActionPlan": "mcclient.jar uploaded for review/change", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Antoine Chesse", 
        "OwnerEmail": "Antoine.Chesse@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 91, 
        "SrNumber": "86287142", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|7.4.1-58|7.4.101-58]", 
        "WhiteBoard": "2017-08-04 (EK): Follow-up sent;", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "NDMP Isilon", 
        "CustLoc": "APJ", 
        "CustomerName": "DEPARTMENT OF EDUCATION - East Perth", 
        "Desc": "NDMP backup failed with exceptions", 
        "EnggLoc": "---", 
        "Esc": 29245, 
        "EscAge": 72, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment #32: Confirm backup policy and whether there is the file '0H4S18WO1D1.MSG' on the backup 2684.", 
        "NextUpdateDate": "06-30", 
        "OtherAssignee": "", 
        "Owner": "Roy Tian", 
        "OwnerEmail": "Roy.Tian@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 169, 
        "SrNumber": "06441124", 
        "Team": "SPT", 
        "Versions": "[7.1.1-145|---|7.1.101-145]", 
        "WhiteBoard": "2017-06-22 (EK): waiting; esc.sev++ wn rdy.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "CA Dept of State Hospitals (DSH-Sacramento)", 
        "Desc": "SR 85946540 - Av2AvDD Migration - Engineering mcserver jar file for Av2AvDD mixed backups on 7.3.0.x", 
        "EnggLoc": "---", 
        "Esc": 29254, 
        "EscAge": 71, 
        "Mod": 2, 
        "NextUpdateActionPlan": "Comment#25\r\n  - Last SR Update 06/20", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "Juan Maldonado", 
        "OwnerEmail": "juan.c.maldonado@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 110, 
        "SrNumber": "85946540", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|---]", 
        "WhiteBoard": "2017-06-27 (EK): esc.sev++ wn rdy.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "DIGITAL RIVER INC", 
        "Desc": "ipmiutil: igetevent-gen4t: MAJ BMC Internal HW Watchdog Trip #e1 Cold Reset Mode. Event 52701", 
        "EnggLoc": "IRVN", 
        "Esc": 29276, 
        "EscAge": 69, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Support: \r\n- Provide FA Information. \r\n\r\nSystems:\r\n- Once received, existing SP for FA to try and reproduce in-house.", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Thayne Forbes", 
        "OwnerEmail": "Thayne.Forbes@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 70, 
        "SrNumber": "86664206", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|---|---]", 
        "WhiteBoard": "RCA (SR still open); 2017-07-04;(NJ) Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "USPS Eagan ECS Data Protection", 
        "Desc": "Significant higher loads on 6 newer nodes with GT08 firmware during GC", 
        "EnggLoc": "---", 
        "Esc": 29280, 
        "EscAge": 68, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Monitoring.", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Christina Dunlop", 
        "OwnerEmail": "christina.dunlop@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 82, 
        "SrNumber": "86417522", 
        "Team": "SPT", 
        "Versions": "[7.1.2-21|---|---]", 
        "WhiteBoard": "2017-07-04 (NJ): CAC E2; monitor wt/SPT; Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "AvVSS", 
        "CustLoc": "ALL", 
        "CustomerName": "ENERGYAUSTRALIA", 
        "Desc": "SR 86583074 || BMR failed with error \"No disk that can be used for recovering the system disk can be found\"", 
        "EnggLoc": "---", 
        "Esc": 29285, 
        "EscAge": 68, 
        "Mod": 3, 
        "NextUpdateActionPlan": "- Comment#39", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Darlene Li", 
        "OwnerEmail": "darlene.li@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S1", 
        "SrAge": 74, 
        "SrNumber": "86583074", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.1.102-21]", 
        "WhiteBoard": "2017-07-18 (EK): last updt 0713", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Systems", 
        "CustLoc": "EMEA", 
        "CustomerName": "CNAF CERTIN", 
        "Desc": "Gen4s Utility node became unresponsive", 
        "EnggLoc": "---", 
        "Esc": 29289, 
        "EscAge": 67, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Comment#4 suggestions.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Robert Jesionowski", 
        "OwnerEmail": "robert.jesionowski@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 70, 
        "SrNumber": "07496168", 
        "Team": "SPT", 
        "Versions": "[7.1.2-21|---|---]", 
        "WhiteBoard": "2017-08-04 (EK): Last updt 0713; esc.sev++ wn rdy", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 7, 
        "CompName": "Systems", 
        "CustLoc": "EMEA", 
        "CustomerName": "Thomson Reuters - UK1 CPS", 
        "Desc": "RCA:Two nodes went offline shortly after consistency check", 
        "EnggLoc": "---", 
        "Esc": 29314, 
        "EscAge": 63, 
        "Mod": 7, 
        "NextUpdateActionPlan": "-Follow-up with Intel\r\n-Update ESC with FA results", 
        "NextUpdateDate": "07-19", 
        "OtherAssignee": "", 
        "Owner": "Vu Duong", 
        "OwnerEmail": "vu.duong@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 66, 
        "SrNumber": "07540157", 
        "Team": "DEV", 
        "Versions": "[7.1.2-21|---|---]", 
        "WhiteBoard": "2017-07-27 (BP): CAC E2; sev + + EOQ;wt/Vu", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Replicator", 
        "CustLoc": "NA", 
        "CustomerName": "MAJOR LEAGUE BASEBALL", 
        "Desc": "Sev S2 - PR 9023 - SCR - Replication - SR# 86607000 - Replication Failing", 
        "EnggLoc": "---", 
        "Esc": 29341, 
        "EscAge": 61, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Comment#23", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "Kerry Li", 
        "OwnerEmail": "Kerry.Li@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S1", 
        "SrAge": 74, 
        "SrNumber": "86607000", 
        "Team": "DEV", 
        "Versions": "[7.1.2-21|7.1.2-21|---]", 
        "WhiteBoard": "2017-07-24 (EK): last updt to SR 0714; esc.sev++ wn rdy", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Client Installation (Windows)", 
        "CustLoc": "NA", 
        "CustomerName": "", 
        "Desc": "EMC Avamar for Windows Setup Wizard ended prematurely when attempting to upgrade from 7.0 to 7.1.102.21", 
        "EnggLoc": "---", 
        "Esc": 29348, 
        "EscAge": 60, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Comment#19", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Sasha Curtis", 
        "OwnerEmail": "sasha.curtis@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 91, 
        "SrNumber": "06980579, 07019203", 
        "Team": "SPT", 
        "Versions": "[---|---|7.1.102-21]", 
        "WhiteBoard": "2017-08-04:(EK) Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "Bank of America", 
        "Desc": "VM Backup sits waiting queued until proxy avagent restarted", 
        "EnggLoc": "CCOE", 
        "Esc": 29350, 
        "EscAge": 60, 
        "Mod": 3, 
        "NextUpdateActionPlan": "- Apply hotfix Bug 284655", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Johnathan Copeland", 
        "OwnerEmail": "johnathan.copeland@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 60, 
        "SrNumber": "86780050", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|---]", 
        "WhiteBoard": "2017-07-12:(NJ) Follow-up #3 sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "MCCLI", 
        "CustLoc": "EMEA", 
        "CustomerName": "ING-WP-EHC", 
        "Desc": "sometimes, mccli command returns error: FIPS 140-2 mode is not supported on Java 7. Please install supported version of Java on the client machine, or turn off this mode on the server.", 
        "EnggLoc": "---", 
        "Esc": 29398, 
        "EscAge": 53, 
        "Mod": 3, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-28", 
        "OtherAssignee": "", 
        "Owner": "Mamta Sahay", 
        "OwnerEmail": "mamta.sahay@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 67, 
        "SrNumber": "86731424", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|7.3.100-233]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "Eli Lilly Z1 c/o Lifeline (Eastgate)", 
        "Desc": "Avamar 7.4.1-58: Hfscheck fails with error MSG_ERR_CMD_FAIL / MSG_ERR_IO_ERROR", 
        "EnggLoc": "---", 
        "Esc": 29402, 
        "EscAge": 53, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "David Yang", 
        "OwnerEmail": "David.Yang@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 57, 
        "SrNumber": "86910778", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|---|---]", 
        "WhiteBoard": "2017-07-04:(NJ) Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Workflow", 
        "CustLoc": "NA", 
        "CustomerName": "AT&T", 
        "Desc": "viewuser passwords are not working after upgrade to 7.3.1-125", 
        "EnggLoc": "---", 
        "Esc": 29410, 
        "EscAge": 50, 
        "Mod": 3, 
        "NextUpdateActionPlan": "No update since 06/21", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Villanueva, Danny", 
        "OwnerEmail": "danny.villanueva@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S5", 
        "SrAge": 53, 
        "SrNumber": "07678844", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|---]", 
        "WhiteBoard": "2017-07-04:(NJ) Follow-up sent3", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "EBR VSphere Web Client Plug-In", 
        "CustLoc": "APJ", 
        "CustomerName": "IMPERIAL PACIFIC INTERNATIONAL HOLDINGS LIMITED", 
        "Desc": "PR 9234: SCR - WebRestore - SR<86944920> - EBR ISSUE", 
        "EnggLoc": "---", 
        "Esc": 29412, 
        "EscAge": 50, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "Greg Sparks", 
        "Owner": "Felix Cheng", 
        "OwnerEmail": "felix.cheng@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 55, 
        "SrNumber": "86944920", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.100-207]", 
        "WhiteBoard": "2017-07-17:(NJ) Not a product issue; info provided; will help Resolve soon", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 5, 
        "CompName": "AvVSS", 
        "CustLoc": "NA", 
        "CustomerName": "Dodge & Cox", 
        "Desc": "WC - Win DR Restore - SR<86976188> - avvss backups on Domain Controllers running slow when \"perform_dr_backup\" set to false", 
        "EnggLoc": "---", 
        "Esc": 29441, 
        "EscAge": 47, 
        "Mod": 5, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "06-29", 
        "OtherAssignee": "", 
        "Owner": "Srikanta kumar", 
        "OwnerEmail": "srikanta.kumar@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 53, 
        "SrNumber": "86976188", 
        "Team": "DEV", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "DPN Management Console (MCC MCS)", 
        "CustLoc": "NA", 
        "CustomerName": "UPS", 
        "Desc": "MCGUI via jnlp does not show activities.", 
        "EnggLoc": "---", 
        "Esc": 29448, 
        "EscAge": 46, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#11", 
        "NextUpdateDate": "07-28", 
        "OtherAssignee": "", 
        "Owner": "Tom George", 
        "OwnerEmail": "tom.george@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S2", 
        "SrAge": 95, 
        "SrNumber": "07560387", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|7.4.1-58|---]", 
        "WhiteBoard": "2017-08-03 (BP):CAC E2;sev ++;wt/HF", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 15, 
        "CompName": "Avplatform", 
        "CustLoc": "NA", 
        "CustomerName": "Viawest", 
        "Desc": "Clash Privilege elevation Vulnerability on Avamar", 
        "EnggLoc": "---", 
        "Esc": 29458, 
        "EscAge": 43, 
        "Mod": 3, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-19", 
        "OtherAssignee": "", 
        "Owner": "Robert Jesionowski", 
        "OwnerEmail": "robert.jesionowski@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S3", 
        "SrAge": 47, 
        "SrNumber": "87088358, 07729129", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MC", 
        "CustLoc": "EMEA", 
        "CustomerName": "Bank Millenium", 
        "Desc": "MCS restore of SQL backups not possible if the Database has 13000 files (mdf/ldf/ndf)", 
        "EnggLoc": "---", 
        "Esc": 29465, 
        "EscAge": 43, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#23/24.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Nick Mostepan", 
        "OwnerEmail": "nick.mostepan@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 55, 
        "SrNumber": "86947552", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "2017-07-04:(NJ) Follow-up sent", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCCLI", 
        "CustLoc": "NA", 
        "CustomerName": "Kentucky Farm Bureau Insurance Agency, Inc", 
        "Desc": "MCCLI VM Restore Fails Finding Proxy 30931,Failed to initiate virtual machine backup or restore", 
        "EnggLoc": "---", 
        "Esc": 29475, 
        "EscAge": 42, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "06-27", 
        "OtherAssignee": "", 
        "Owner": "Leon Liu", 
        "OwnerEmail": "Leon.Liu@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 61, 
        "SrNumber": "07597534", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "2017-07-04:(NJ) w/t on cust", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "Avplatform", 
        "CustLoc": "EMEA", 
        "CustomerName": "Telefonica Ericson Unica Test Bed Alcobendas, ES", 
        "Desc": "OWASP scan in Avamar 7.3 reports several issues", 
        "EnggLoc": "---", 
        "Esc": 29498, 
        "EscAge": 40, 
        "Mod": 2, 
        "NextUpdateActionPlan": "Comment#12.", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Robert Jesionowski", 
        "OwnerEmail": "robert.jesionowski@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S2", 
        "SrAge": 75, 
        "SrNumber": "86583918", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|---|---]", 
        "WhiteBoard": "2017-07-04:(NJ) next steps?", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "MC", 
        "CustLoc": "EMEA", 
        "CustomerName": "GBP BRED VULCAIN CHANTEPIE", 
        "Desc": "Avamar 7.4.1-58: MCS running out of memory while trying to load the objects from PSQL output", 
        "EnggLoc": "---", 
        "Esc": 29531, 
        "EscAge": 35, 
        "Mod": 0, 
        "NextUpdateActionPlan": "Comment#22 - Comment#24", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Antoine Chesse", 
        "OwnerEmail": "Antoine.Chesse@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S5", 
        "SrAge": 81, 
        "SrNumber": "86478142", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|7.4.1-58|---]", 
        "WhiteBoard": "Further discussion to be had", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "Lowe's Companies Inc", 
        "Desc": "GC is unable to finish due to Operation time limit reached. gc did not complete", 
        "EnggLoc": "---", 
        "Esc": 29532, 
        "EscAge": 35, 
        "Mod": 3, 
        "NextUpdateActionPlan": "- Looking to rule in/out the use of HF 275857 which helps to address the\r\n  underlying cause here.\r\n- SR update 0728 waiting to apply hotfix, etc.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Marcus Henderson", 
        "OwnerEmail": "Marcus.Henderson@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 36, 
        "SrNumber": "87301564", 
        "Team": "SPT", 
        "Versions": "[7.1.2-21|---|---]", 
        "WhiteBoard": "2017-08-02 (EK): Wt/cust; esc.sev++ wn nec.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Utilities", 
        "CustLoc": "EMEA", 
        "CustomerName": "FUJITSU SERVICES OY", 
        "Desc": "Sev S3 - SCR - User Account - SR#86789798 - change-passwords script completes but leaves viewuser password unencrypted in mcserver.xml", 
        "EnggLoc": "---", 
        "Esc": 29534, 
        "EscAge": 35, 
        "Mod": 3, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "Roger Zee", 
        "Owner": "Tom George", 
        "OwnerEmail": "tom.george@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 63, 
        "SrNumber": "07564690", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "Atos S.A.", 
        "Desc": "Need RCA done for Node 0.11 Going offline while restarting Node 0.9 that had a Chassis replacement due to battery Issues", 
        "EnggLoc": "---", 
        "Esc": 29554, 
        "EscAge": 33, 
        "Mod": 2, 
        "NextUpdateActionPlan": "- Request to update Proactive check", 
        "NextUpdateDate": "07-28", 
        "OtherAssignee": "", 
        "Owner": "Ian Anderson", 
        "OwnerEmail": "Anderson_Ian@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 34, 
        "SrNumber": "07861674", 
        "Team": "APP", 
        "Versions": "[7.1.2-21|---|---]", 
        "WhiteBoard": "2017-07-18 (BP): CAC E2 ; wt/DEV", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "LATEC", 
        "Desc": "Customer is receiving power supply alerts in the GUI[Same grid as in ESC 28682]", 
        "EnggLoc": "---", 
        "Esc": 29557, 
        "EscAge": 33, 
        "Mod": 3, 
        "NextUpdateActionPlan": "- When were the power supplies replaced on prlabavn02?\r\n- What is the FA tracking for the returned power supplies for server prlabavn02?", 
        "NextUpdateDate": "07-13", 
        "OtherAssignee": "", 
        "Owner": "Roger Zee", 
        "OwnerEmail": "zee_roger@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 42, 
        "SrNumber": "86903944", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "VMWare Image", 
        "CustLoc": "NA", 
        "CustomerName": "BANK OF AMERICA_SMS MANAGED SERVICES_SANDSTON", 
        "Desc": "VC Certificate change causes backup failure . Requires new thumbprint", 
        "EnggLoc": "---", 
        "Esc": 29559, 
        "EscAge": 33, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Assigning to product management (Yatin) to determine disposition of bug#267379, and direct this escalation toward closure acceptable by the bank.\r\n\r\n- Further technical discussions as to potential solutions", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Yatin Patil", 
        "OwnerEmail": "Yatin.Patil@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 33, 
        "SrNumber": "07877396", 
        "Team": "DEV", 
        "Versions": "[---|7.3.1-125|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Avtar", 
        "CustLoc": "NA", 
        "CustomerName": "CSC", 
        "Desc": "PR 9486: WC - SQL - SR<#07810830> - <SQL backup fails: avsql Error <18491>: SQL plug-in will now terminate due to the following avtar error: 'code 0xffffffff:>", 
        "EnggLoc": "---", 
        "Esc": 29562, 
        "EscAge": 33, 
        "Mod": 3, 
        "NextUpdateActionPlan": "- Test binary to be applied", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Nick Mostepan", 
        "OwnerEmail": "nick.mostepan@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 40, 
        "SrNumber": "07810830", 
        "Team": "SPT", 
        "Versions": "[7.2.1-32|---|7.2.101-32]", 
        "WhiteBoard": "2017-08-02 (EK): last SR updt 07/13; esc.sev->SR.sev", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Avplatform", 
        "CustLoc": "APJ", 
        "CustomerName": "WANBISHI ARCHIVES", 
        "Desc": "New Apache vulnerabilities (CVE-2017-3167/CVE-2017-3169/CVE-2017-7679)", 
        "EnggLoc": "---", 
        "Esc": 29565, 
        "EscAge": 32, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Waiting on response from Ahmad for PTF request.", 
        "NextUpdateDate": "08-10", 
        "OtherAssignee": "", 
        "Owner": "Craig Marroquin", 
        "OwnerEmail": "Craig.Marroquin@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S3", 
        "SrAge": 33, 
        "SrNumber": "07871173", 
        "Team": "DEV", 
        "Versions": "[7.2.1-32|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "SSM Health Care Corporation", 
        "Desc": "MCS went down + flushes don't run for periods of time during maintenance", 
        "EnggLoc": "---", 
        "Esc": 29567, 
        "EscAge": 32, 
        "Mod": 2, 
        "NextUpdateActionPlan": "- Comment#9.\r\n- SR indicates related IBU work is in progress.", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Budzianowski, Adam", 
        "OwnerEmail": "adam.budzianowski@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 34, 
        "SrNumber": "07861505", 
        "Team": "SPT", 
        "Versions": "[---|7.2.1-31|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "VMWare File", 
        "CustLoc": "EMEA", 
        "CustomerName": "EJIE S.A.", 
        "Desc": "7.4 FLR with ACL does not work - The operation is not supported for the specified parameters", 
        "EnggLoc": "---", 
        "Esc": 29573, 
        "EscAge": 30, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- SR: 08/03 Applied patch where:\r\n\r\n> -Logged in with the customer \r\n\r\n> -- applied the new patch, the customer needs permission from the customer to test the FLR\r\n> awaiting on the customer;s feedback", 
        "NextUpdateDate": "08-09", 
        "OtherAssignee": "", 
        "Owner": "Reem Tarek", 
        "OwnerEmail": "Reem.Tarek@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 69, 
        "SrNumber": "86682324", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|---|7.4.101-58]", 
        "WhiteBoard": "2017-08-01 (EK): no updt since 0720; esc.sev++ wn nec.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "DPN Clients", 
        "CustLoc": "NA", 
        "CustomerName": "SP Customer", 
        "Desc": "SR# 85247872/07871688 - SP customer - Security vulnerabilities on Avamar proxies with the latest OS Security Rollup (2016Q4) installed. Reference ESC: 28669", 
        "EnggLoc": "---", 
        "Esc": 29575, 
        "EscAge": 29, 
        "Mod": 2, 
        "NextUpdateActionPlan": "- Corresponding SR closed: 24-Mar-2017 07:20(?)  Is there a new one tracking this issue?", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "Christopher Hawkinson", 
        "Owner": "Jerome Fillon", 
        "OwnerEmail": "jerome.fillon@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S5", 
        "SrAge": 33, 
        "SrNumber": "07871688", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "2017-08-01 (EK): Last updt 0725; esc.sev++ wn rdy.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "VMware Deployment Manager", 
        "CustLoc": "EMEA", 
        "CustomerName": "LANCASHIRE TEACHING HOSPITALS", 
        "Desc": "avamar-tomcat asserts then stop running after DPM internal failure", 
        "EnggLoc": "CCOE", 
        "Esc": 29586, 
        "EscAge": 29, 
        "Mod": 3, 
        "NextUpdateActionPlan": "Comment#8.  Re-assigning to owner of both SRs as Phil is OOO.", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Budzianowski, Adam", 
        "OwnerEmail": "adam.budzianowski@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 35, 
        "SrNumber": "87314016, 07851077", 
        "Team": "SPT", 
        "Versions": "[---|---|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCS - database", 
        "CustLoc": "EMEA", 
        "CustomerName": "DTDC EXPRESS LIMITED", 
        "Desc": "MCS flushes get delayed intermittently when userinfo poller task is running causing MCS GUI events report \u201cFlush of Administrator Server data to server is overdue\u201d errors", 
        "EnggLoc": "---", 
        "Esc": 29588, 
        "EscAge": 28, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- To provide DD bundles.", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "George Gabra", 
        "OwnerEmail": "george.gabra@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 48, 
        "SrNumber": "87082630", 
        "Team": "SPT", 
        "Versions": "[7.2.0-401|7.2.0-401|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Avtar", 
        "CustLoc": "NA", 
        "CustomerName": "GRDC LIPPERT COMPONENTS C/O US SIGNAL DATA CENTER", 
        "Desc": "Regarding VDDK:VixDiskLib: VixDiskLib_Close: Close disk< avtar STOPPED PROCESSING, no progress>", 
        "EnggLoc": "---", 
        "Esc": 29595, 
        "EscAge": 28, 
        "Mod": 3, 
        "NextUpdateActionPlan": "@Dev:\r\n- Working on what would eventually be a hotfix.\r\n- Information about VMware Bug id forthcoming.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "Qingxiao Zheng", 
        "Owner": "Julio Acevedo", 
        "OwnerEmail": "acevedodeleon_julio@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 66, 
        "SrNumber": "07540029", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|7.4.1-58|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "RMAN Module", 
        "CustLoc": "APJ", 
        "CustomerName": "Henan University", 
        "Desc": "NC - Oracle - SR<#07836165> - <Oracle backup occasionally failing due to avoracle crash>", 
        "EnggLoc": "---", 
        "Esc": 29599, 
        "EscAge": 28, 
        "Mod": 3, 
        "NextUpdateActionPlan": "@Dev: Review Logs", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Preksha Sisodia", 
        "OwnerEmail": "preksha.sisodia@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 36, 
        "SrNumber": "07836165", 
        "Team": "TicketNWuser", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "2017-07-24 (EK): SR Last updt 07/11; esc.sev++ wn rdy", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "Quicken Loans Troy Web Center", 
        "Desc": "MAJ BMC Secondary Firmware Log #e4 CMD Log (as FRU ID of the device:0 Index of the CM ) error & Sensor 'SP_CMD_Vin' has unexpected status of 'cr'", 
        "EnggLoc": "---", 
        "Esc": 29601, 
        "EscAge": 27, 
        "Mod": 1, 
        "NextUpdateActionPlan": "- Replace SP, still determining if Hardware Engineering wants to FA the existing SP.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Vineeth Selvam", 
        "OwnerEmail": "vineeth.selvam@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S2", 
        "SrAge": 28, 
        "SrNumber": "87380098", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "VMWare Image", 
        "CustLoc": "NA", 
        "CustomerName": "OneMain Holdings, Inc.", 
        "Desc": "<avvcbimage FATAL <5889>: Fatal signal 11 in pid 2687> crashes causes snapshot to be left behind", 
        "EnggLoc": "---", 
        "Esc": 29617, 
        "EscAge": 26, 
        "Mod": 3, 
        "NextUpdateActionPlan": "Waiting for re-occurrence", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Julio Acevedo", 
        "OwnerEmail": "acevedodeleon_julio@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 33, 
        "SrNumber": "07873337", 
        "Team": "SPT", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCGUI", 
        "CustLoc": "NA", 
        "CustomerName": "US DEPARTMENT OF STATE / GITM", 
        "Desc": "Customer can not access Avamar GUI due to expired cert", 
        "EnggLoc": "---", 
        "Esc": 29620, 
        "EscAge": 26, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Brandon Hawn", 
        "OwnerEmail": "Brandon.Hawn@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 45, 
        "SrNumber": "07740510", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|---]", 
        "WhiteBoard": "2017-07-18 (BP): CAC E2; wt/SPT", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "Avplatform", 
        "CustLoc": "NA", 
        "CustomerName": "Bank of New York (CNJPC)", 
        "Desc": "Node 0.9 GSAN restart failed at the startup phase", 
        "EnggLoc": "---", 
        "Esc": 29626, 
        "EscAge": 25, 
        "Mod": 0, 
        "NextUpdateActionPlan": "Continued monitoring.", 
        "NextUpdateDate": "07-28", 
        "OtherAssignee": "", 
        "Owner": "Haral Tsitsivas", 
        "OwnerEmail": "haral.tsitsivas@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S3", 
        "SrAge": 30, 
        "SrNumber": "07891956", 
        "Team": "DEV", 
        "Versions": "[7.0.2-47|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "WVM (Windows VMware GLR Plug-in)", 
        "CustLoc": "EMEA", 
        "CustomerName": "DHL AVIATION", 
        "Desc": "ALR (VMWare GLR) not able to mount windows vmdk for backups stored on DD", 
        "EnggLoc": "---", 
        "Esc": 29632, 
        "EscAge": 22, 
        "Mod": 0, 
        "NextUpdateActionPlan": "Comment#18", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Krishnendu Bagchi", 
        "OwnerEmail": "Krishnendu.Bagchi@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 46, 
        "SrNumber": "87124942", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "2017-08-01 (EK): Last updt 0722; esc.sev++ wn rdy.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "OP2 Minnetonka", 
        "Desc": "SCR - MCS -  - SR#07676748- Unable to Browse Backups for Container Clients in 7.3 GUI, receiving 21007 Administration Error with \"java.rmi.NoSuchObjectException: no such object in table\" message in GUI logs", 
        "EnggLoc": "---", 
        "Esc": 29634, 
        "EscAge": 22, 
        "Mod": 2, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Rashaun Evans", 
        "OwnerEmail": "Rashaun.Evans@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 53, 
        "SrNumber": "07676748", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|---]", 
        "WhiteBoard": "2017-08-01 (EK): last updt 0727; esc.sev++ wn nec.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "NDMP Celerra", 
        "CustLoc": "NA", 
        "CustomerName": "CENVEO", 
        "Desc": "NDMP backups finishes but avtar hangs with ndmp_history::processhist::body handled 223193 NDMPHISTLISTLINE messages, which is all that readhist sent", 
        "EnggLoc": "---", 
        "Esc": 29636, 
        "EscAge": 22, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Action Plans:\r\n> I think now we can suggest customer check those two deep folders, are they expected to be that deep?\r\n> Can they remove those deep folders or change the path to a less deep path?", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Sean Strohak", 
        "OwnerEmail": "sean.strohak@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 55, 
        "SrNumber": "07654833", 
        "Team": "SPT", 
        "Versions": "[---|---|7.2.100-401]", 
        "WhiteBoard": "2017-07-24 (EK): SR last updt 0713; esc.sev++ wn rdy.", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "DB2", 
        "CustLoc": "EMEA", 
        "CustomerName": "CLYDE BERGEMANN GMBH", 
        "Desc": "DB2 full online backup malformed --history", 
        "EnggLoc": "---", 
        "Esc": 29642, 
        "EscAge": 21, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Carlo Zanelli", 
        "OwnerEmail": "carlo.zanelli@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 26, 
        "SrNumber": "87489850", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "Emory University Hospital", 
        "Desc": "SP Service LED is amber on a Gen4T node", 
        "EnggLoc": "---", 
        "Esc": 29650, 
        "EscAge": 20, 
        "Mod": 1, 
        "NextUpdateActionPlan": "SR Indicates continued work with CE.", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Robert Jesionowski", 
        "OwnerEmail": "robert.jesionowski@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 23, 
        "SrNumber": "87545466", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 6, 
        "CompName": "Hyper-V", 
        "CustLoc": "NA", 
        "CustomerName": "TOWN OF FLOWER MOUND", 
        "Desc": "Hyper-V GLR failing for one VM failing with \u201cUnable to browse hard disk since the VHD is not in mounted state\u201d", 
        "EnggLoc": "---", 
        "Esc": 29652, 
        "EscAge": 20, 
        "Mod": 5, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-20", 
        "OtherAssignee": "Suman Tokuri", 
        "Owner": "John Vu", 
        "OwnerEmail": "John.Vu@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 55, 
        "SrNumber": "07654717", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|---|7.4.101-58]", 
        "WhiteBoard": "2017-07-20 (BP): CAC E2; wt/DEV", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "NDMP Celerra", 
        "CustLoc": "NA", 
        "CustomerName": "Ally Financial San Antonio - Direct", 
        "Desc": "PR 9548: NC - NDMP Celerra - SR<87333214> - <NDMP backups failing > avtar read found bad pas header", 
        "EnggLoc": "---", 
        "Esc": 29660, 
        "EscAge": 19, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#6. \r\n  - SR last update 07/24/2017 07:04 AM", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Michael Stull", 
        "OwnerEmail": "michael.stull@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 27, 
        "SrNumber": "87333214", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "Bank of New York (CNJPC)", 
        "Desc": "RCA - Node 0.0 Offline during cgsan startup", 
        "EnggLoc": "---", 
        "Esc": 29680, 
        "EscAge": 17, 
        "Mod": 2, 
        "NextUpdateActionPlan": "@Systems Team: Per the Server Team, would you have any thoughts?", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Danny Lovelady", 
        "OwnerEmail": "danny.lovelady@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S5", 
        "SrAge": 18, 
        "SrNumber": "08021663", 
        "Team": "SPT", 
        "Versions": "[7.0.1-61|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "Replicator", 
        "CustLoc": "EMEA", 
        "CustomerName": "Synthos", 
        "Desc": "Replication target capacity spiked significantly relative to source - trying to identify the cause", 
        "EnggLoc": "---", 
        "Esc": 29681, 
        "EscAge": 15, 
        "Mod": 0, 
        "NextUpdateActionPlan": "Confirm whether the replicate + capacity-related rollback scenario is the cause of the disparity", 
        "NextUpdateDate": "07-24", 
        "OtherAssignee": "", 
        "Owner": "Nicholas Ricioppo", 
        "OwnerEmail": "ricioppo_nicholas@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S3", 
        "SrAge": 26, 
        "SrNumber": "07952045", 
        "Team": "SPT", 
        "Versions": "[7.1.1-141|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "DPN Management Console (MCC MCS)", 
        "CustLoc": "APJ", 
        "CustomerName": "Alphawest (VBLOCK) // Port Melbourne", 
        "Desc": "MCS ran out of java heap size when FAILED to get VC Connections", 
        "EnggLoc": "---", 
        "Esc": 29687, 
        "EscAge": 15, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Assigning to case owner Kevin Lv.", 
        "NextUpdateDate": "07-27", 
        "OtherAssignee": "", 
        "Owner": "Kevin Lv", 
        "OwnerEmail": "kevin.lv@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S2", 
        "SrAge": 36, 
        "SrNumber": "87285312", 
        "Team": "SPT", 
        "Versions": "[---|7.4.1-58|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "Datadomain Integration", 
        "CustLoc": "APJ", 
        "CustomerName": "UTC/CSC MS Utility Hong Kong, HK", 
        "Desc": "WC-SR-87615444  The MD5 result will be changed after the file be restore from DD", 
        "EnggLoc": "---", 
        "Esc": 29689, 
        "EscAge": 15, 
        "Mod": 2, 
        "NextUpdateActionPlan": "Mtime is not changed even if file's modified in the source. Let customer confirm and if so please check VNX mount point or SQLServer configuration.", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "Ryan Cao", 
        "OwnerEmail": "ryan.cao@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S1", 
        "SrAge": 19, 
        "SrNumber": "87615444", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCGUI - Replicate", 
        "CustLoc": "EMEA", 
        "CustomerName": "Walgreens Boots Alliance Servies", 
        "Desc": "Virtual Containers are not being replicated", 
        "EnggLoc": "---", 
        "Esc": 29691, 
        "EscAge": 14, 
        "Mod": 2, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Ahmed Tolba", 
        "OwnerEmail": "ahmed.tolba@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 26, 
        "SrNumber": "87501492", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "Document", 
        "CustLoc": "NA", 
        "CustomerName": "SHAZAM, INC.", 
        "Desc": "ICMP packets are being sent from Avamar utility node to the clients", 
        "EnggLoc": "---", 
        "Esc": 29695, 
        "EscAge": 14, 
        "Mod": 0, 
        "NextUpdateActionPlan": "Email sent regarding whether we should document this in the PSG (Comment#6/Comment#7)", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Haral Tsitsivas", 
        "OwnerEmail": "haral.tsitsivas@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S5", 
        "SrAge": 29, 
        "SrNumber": "07912047", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "NDMP Celerra", 
        "CustLoc": "NA", 
        "CustomerName": "Kaiser Foundation - Silver Spring", 
        "Desc": "PR 9183: NC - NDMP Celerra - SR07631991 - Multiple backups are failing with error 'Lost pipe to avtar: code 32: Broken pipe', 'Premature end of child.'", 
        "EnggLoc": "---", 
        "Esc": 29706, 
        "EscAge": 13, 
        "Mod": 2, 
        "NextUpdateActionPlan": "Hi Sean,\r\n\r\nAction Item 1:\r\nPlease recommend the customer to increase the RAM to around 128G-256G\r\n\r\nAction item 2:\r\nTo advice customer and VNX team to upgrade the Celerra Server.T.6.0.70.4 to  T.7.X versions.\r\n\r\nAction item 3:\r\nCould the customer try to move at least 30 million files to another volume B, then backup can be performed on the hosncp0812036 volume and volume B with only one stream separately .  In this way ,avtar is likely to complete the backups for current memory allocation.", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Sean Strohak", 
        "OwnerEmail": "sean.strohak@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 57, 
        "SrNumber": "07631991", 
        "Team": "SPT", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "AT&T INC.", 
        "Desc": "issues with usersettings.cfg encrypted password after upgrade to 7.3.1", 
        "EnggLoc": "---", 
        "Esc": 29710, 
        "EscAge": 13, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#19's questions I believe should be for the Core team.", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "Goran Arapovic", 
        "Owner": "Ewa Anderson", 
        "OwnerEmail": "ewa.anderson@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S1", 
        "SrAge": 12, 
        "SrNumber": "08086923", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "AvFS", 
        "CustLoc": "EMEA", 
        "CustomerName": "FICOLO OY", 
        "Desc": "Hyper-V GLR browse fails \"Failed to browse into virtual machine\"", 
        "EnggLoc": "---", 
        "Esc": 29712, 
        "EscAge": 12, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-31", 
        "OtherAssignee": "", 
        "Owner": "Aaron Lin", 
        "OwnerEmail": "Aaron.Lin@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S1", 
        "SrAge": 29, 
        "SrNumber": "87415334", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|---|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Exchange", 
        "CustLoc": "NA", 
        "CustomerName": "Miron Construction", 
        "Desc": "WC - Exchange GLR - SR#07863514 - Avamar 7.5.100-183 Exchange GLR For ItemPoint Ignores itempoint_logs_recovery_path directive", 
        "EnggLoc": "---", 
        "Esc": 29717, 
        "EscAge": 12, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-31", 
        "OtherAssignee": "", 
        "Owner": "Russ Logsdon", 
        "OwnerEmail": "russ.logsdon@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 33, 
        "SrNumber": "07863514", 
        "Team": "SPT", 
        "Versions": "[7.5.0-183|---|7.5.100-183]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Avtar", 
        "CustLoc": "NA", 
        "CustomerName": "VENTURE TECHNOLOGIES", 
        "Desc": "Exchange Public Folder backup fails with \"INTERNAL ERROR\"", 
        "EnggLoc": "---", 
        "Esc": 29722, 
        "EscAge": 12, 
        "Mod": 1, 
        "NextUpdateActionPlan": "@Dev to create hotfix.", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Tushar Dethe", 
        "OwnerEmail": "tushar.dethe@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 21, 
        "SrNumber": "08003034", 
        "Team": "TicketNWuser", 
        "Versions": "[7.4.1-58|---|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Exchange", 
        "CustLoc": "NA", 
        "CustomerName": "VENTURE TECHNOLOGIES", 
        "Desc": "Restore to RDB fails with \"VSS writer did not find anything to restore\"", 
        "EnggLoc": "---", 
        "Esc": 29723, 
        "EscAge": 12, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "07-31", 
        "OtherAssignee": "", 
        "Owner": "John Vu", 
        "OwnerEmail": "John.Vu@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 21, 
        "SrNumber": "08003034", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|---|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "Bank of New York (TPC)", 
        "Desc": "Updates and changes to Modify-Snapups script", 
        "EnggLoc": "---", 
        "Esc": 29738, 
        "EscAge": 8, 
        "Mod": 2, 
        "NextUpdateActionPlan": "Assigning first to the Systems Team based on check-in history.\r\n\r\n1) Could you provide what would be a hotfixed version of\r\n   modify-snapups?  The proposals made earlier were based on what was\r\n   implemented years ago, and also based on the issue described, but\r\n   would like the formal input of the Development Team.\r\n\r\n2) Based on the diffs, I assume that we could safely create a\r\n   modify-snapups based on the most recent version of the script (as\r\n   it hasn't been updated since 2012).", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "David Yang", 
        "OwnerEmail": "David.Yang@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S2", 
        "SrAge": 12, 
        "SrNumber": "87726438", 
        "Team": "DEV", 
        "Versions": "[7.0.1-61|7.0.1-61|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Hyper-V", 
        "CustLoc": "NA", 
        "CustomerName": "CYBERSHARKS.NET", 
        "Desc": "Hyper-V backups of some VMs fail with \"Could not create backup checkpoint for virtual machine\"", 
        "EnggLoc": "---", 
        "Esc": 29739, 
        "EscAge": 8, 
        "Mod": 1, 
        "NextUpdateActionPlan": "Comment#4", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "John Vu", 
        "OwnerEmail": "John.Vu@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 13, 
        "SrNumber": "08082337", 
        "Team": "SPT", 
        "Versions": "[7.5.0-183|---|7.5.100-183]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Avtar", 
        "CustLoc": "APJ", 
        "CustomerName": "HI INVESTMENT & SECURITIES", 
        "Desc": "HPUX - SR<#07625988> - <HP Unix client backup failed>", 
        "EnggLoc": "---", 
        "Esc": 29742, 
        "EscAge": 7, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Will Zhao", 
        "OwnerEmail": "will.zhao@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 25, 
        "SrNumber": "07961655", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|7.3.1-125|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "AvVSS", 
        "CustLoc": "EMEA", 
        "CustomerName": "FUJITSU SERVICES OY", 
        "Desc": "PR 9728: WC - Win DR Backup - SR 87462712 - VSS backup on Domain controllers uses 100% CPU if the option \"Create Disaster Recovery Backup\" is NOT selected.", 
        "EnggLoc": "---", 
        "Esc": 29743, 
        "EscAge": 7, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Srikanta kumar", 
        "OwnerEmail": "srikanta.kumar@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 28, 
        "SrNumber": "87462712", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|---|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "Avtar", 
        "CustLoc": "EMEA", 
        "CustomerName": "Etisalat Eng. Cloud - Abu Dhabi", 
        "Desc": "Arabic Named Folders not backing up in Cluster server", 
        "EnggLoc": "---", 
        "Esc": 29744, 
        "EscAge": 7, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Bangalore Dev for MS Apps", 
        "OwnerEmail": "avamar.msapps.blrdev@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 40, 
        "SrNumber": "87226686", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|---|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "gsan", 
        "CustLoc": "EMEA", 
        "CustomerName": "Dana-Albarus S/A Industria e Comercio", 
        "Desc": "ERROR tchunklist::lookup bad chunkid=50183 and 59515", 
        "EnggLoc": "---", 
        "Esc": 29749, 
        "EscAge": 7, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Kerry Li", 
        "OwnerEmail": "Kerry.Li@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 15, 
        "SrNumber": "87750022", 
        "Team": "DEV", 
        "Versions": "[7.2.1-32|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "MCS - security", 
        "CustLoc": "NA", 
        "CustomerName": "CNIC-ISHORE", 
        "Desc": "Unable to configure CAC/PIV solution.", 
        "EnggLoc": "---", 
        "Esc": 29751, 
        "EscAge": 7, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Yatin Patil", 
        "OwnerEmail": "Yatin.Patil@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 99, 
        "SrNumber": "7192299", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|7.4.1-58|7.4.101-58]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 3, 
        "CompName": "MCGUI", 
        "CustLoc": "NA", 
        "CustomerName": "P&L Technology", 
        "Desc": "Activity window filter does not show complete options", 
        "EnggLoc": "---", 
        "Esc": 29752, 
        "EscAge": 7, 
        "Mod": 3, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Richard Brinkmann", 
        "OwnerEmail": "brinkmann_richard@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 110, 
        "SrNumber": "7086022", 
        "Team": "SPT", 
        "Versions": "[---|7.3.1-125|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "Systems", 
        "CustLoc": "NA", 
        "CustomerName": "USPS", 
        "Desc": "RCA Gen4T node offline", 
        "EnggLoc": "IRVN", 
        "Esc": 29753, 
        "EscAge": 7, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "George Eldridge", 
        "OwnerEmail": "george.eldridge@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 8, 
        "SrNumber": "08126644", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 2, 
        "CompName": "MCS", 
        "CustLoc": "EMEA", 
        "CustomerName": "EMERSON ELECTRIC CO.", 
        "Desc": "7.5 Backup-Restore Operator gets error \u201cThe user has insufficient privileges to access the system resource.\u201d", 
        "EnggLoc": "---", 
        "Esc": 29756, 
        "EscAge": 6, 
        "Mod": 2, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-02", 
        "OtherAssignee": "", 
        "Owner": "Mamta Sahay", 
        "OwnerEmail": "mamta.sahay@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 12, 
        "SrNumber": "08089671", 
        "Team": "SPT", 
        "Versions": "[7.5.0-183|7.5.0-183|7.5.100-183]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "MCS", 
        "CustLoc": "EMEA", 
        "CustomerName": "FEDUK CSC LTD", 
        "Desc": "Power on VM with NICs option doesn't take effect when restoring from remote backup", 
        "EnggLoc": "---", 
        "Esc": 29757, 
        "EscAge": 6, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Boris Lin", 
        "OwnerEmail": "Boris.Lin@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S2", 
        "SrAge": 13, 
        "SrNumber": "87724216", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|7.4.1-58|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "SharePoint", 
        "CustLoc": "NA", 
        "CustomerName": "UNIVERSITY OF HOUSTON SYSTEM", 
        "Desc": "Request to port hotfix #273798 for SharePoint VSS plug-in to 7.3 SP1", 
        "EnggLoc": "---", 
        "Esc": 29758, 
        "EscAge": 6, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "John Vu", 
        "OwnerEmail": "John.Vu@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S5", 
        "SrAge": 12, 
        "SrNumber": "08100935", 
        "Team": "SPT", 
        "Versions": "[7.3.1-125|---|7.3.101-125]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "gsan", 
        "CustLoc": "EMEA", 
        "CustomerName": "EBRC RCS DC", 
        "Desc": "Node rebuild fails with fatal error on 1 stripe", 
        "EnggLoc": "---", 
        "Esc": 29761, 
        "EscAge": 6, 
        "Mod": 1, 
        "NextUpdateActionPlan": "-Upload the correct logs for rebuilding node 0.7\r\n-If the previous rebuild attempt used transplanted disks, attempt to restart, putting aside stripe files for stripes 0.0-13, 0.7-2547, 0.7-1047.", 
        "NextUpdateDate": "08-04", 
        "OtherAssignee": "", 
        "Owner": "Paul Kim", 
        "OwnerEmail": "paul.kim@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S1", 
        "SrAge": 13, 
        "SrNumber": "87694220", 
        "Team": "DEV", 
        "Versions": "[7.2.0-401|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "Workflow", 
        "CustLoc": "EMEA", 
        "CustomerName": "ITaito Oy C/O Equinix Finland Suvilahti", 
        "Desc": "7.4.1 Upgrade workflow failing while preparing system for Operating System update", 
        "EnggLoc": "CCOE", 
        "Esc": 29765, 
        "EscAge": 5, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-10", 
        "OtherAssignee": "", 
        "Owner": "Ahmed Tolba", 
        "OwnerEmail": "ahmed.tolba@emc.com", 
        "ProdName": "Sec", 
        "Severity": "S3", 
        "SrAge": 10, 
        "SrNumber": "87775492", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|7.3.0-233|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "EBRC", 
        "Desc": "Avamar 7.3.x/7.4.x: Requesting improvement(s) for the Data Domain deletion process", 
        "EnggLoc": "---", 
        "Esc": 29768, 
        "EscAge": 5, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-10", 
        "OtherAssignee": "", 
        "Owner": "Elsa Liao", 
        "OwnerEmail": "Elsa.Liao@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S4", 
        "SrAge": 8, 
        "SrNumber": "87799802", 
        "Team": "DEV", 
        "Versions": "[7.4.1-58|7.4.1-58|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "Plains All American", 
        "Desc": "During maintenance activity, trying to browse a backup label in MCGUI in restore tab, under /REPLICATE domain, generates an error: \"Unable to retrieve backup content.\"", 
        "EnggLoc": "---", 
        "Esc": 29769, 
        "EscAge": 5, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "Sailesh Sakaria", 
        "OwnerEmail": "sailesh.sakaria@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 8, 
        "SrNumber": "08088852", 
        "Team": "SPT", 
        "Versions": "[7.1.2-21|7.1.2-21|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "MCS", 
        "CustLoc": "NA", 
        "CustomerName": "INFORMATION MANAGEMENT SYSTEMS INC, HILLSBORO DATACENTER", 
        "Desc": "Avamar 7.4.1-58: Editing data domain fails with error \"Failed to connect to Data Domain system\"", 
        "EnggLoc": "---", 
        "Esc": 29771, 
        "EscAge": 5, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-10", 
        "OtherAssignee": "", 
        "Owner": "Tom George", 
        "OwnerEmail": "tom.george@emc.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 8, 
        "SrNumber": "87803474", 
        "Team": "SPT", 
        "Versions": "[7.4.1-58|7.4.1-58|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "SQL", 
        "CustLoc": "NA", 
        "CustomerName": "SAINT VINCENT HEALTH CTR", 
        "Desc": "PR 9782: WC - SQL - SR<#07935593> - <SQL restore is failing with the error: Logical file 'FORMULARY_log' is not part of database 'Formulary_t2_cmd'. Use RESTORE FILELISTONLY to list the logical file names. >", 
        "EnggLoc": "---", 
        "Esc": 29773, 
        "EscAge": 5, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-07", 
        "OtherAssignee": "", 
        "Owner": "Sunder Andra", 
        "OwnerEmail": "Sunder.Andra@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 28, 
        "SrNumber": "07935593", 
        "Team": "DEV", 
        "Versions": "[---|---|7.1.102-21]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "NDMP Isilon", 
        "CustLoc": "NA", 
        "CustomerName": "LOVE'S TRAVEL STOPS & COUNTRY STORES", 
        "Desc": "PR 9746: NC - NDMP Isilon - SR<08071882> - <avsetupndmp fails modifying a Isilong client>", 
        "EnggLoc": "---", 
        "Esc": 29775, 
        "EscAge": 5, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-14", 
        "OtherAssignee": "", 
        "Owner": "Michael Stull", 
        "OwnerEmail": "michael.stull@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S2", 
        "SrAge": 11, 
        "SrNumber": "08071882", 
        "Team": "SPT", 
        "Versions": "[7.3.0-233|---|7.3.100-233]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "DPN Server (gsan avmaint avmgr dpnutils)", 
        "CustLoc": "NA", 
        "CustomerName": "Cigna", 
        "Desc": "Cigna - Gen4T -  disk failures on multiple nodes, same disks previously replaced", 
        "EnggLoc": "---", 
        "Esc": 29777, 
        "EscAge": 5, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-03", 
        "OtherAssignee": "", 
        "Owner": "DL-F Application Engineering alias", 
        "OwnerEmail": "DL-FApplicationEngineering@emc.com", 
        "ProdName": "AppEng", 
        "Severity": "S3", 
        "SrAge": 5, 
        "SrNumber": "08166718", 
        "Team": "APP", 
        "Versions": "[7.3.0-233|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 1, 
        "CompName": "Workflows", 
        "CustLoc": "NA", 
        "CustomerName": "National Defense University", 
        "Desc": "Intel Block Hotfix 272154: Workflow goes to a non-existent stage 05 and never finishes", 
        "EnggLoc": "---", 
        "Esc": 29784, 
        "EscAge": 4, 
        "Mod": 1, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-11", 
        "OtherAssignee": "", 
        "Owner": "Christopher Hawkinson", 
        "OwnerEmail": "Christopher.Hawkinson@emc.com", 
        "ProdName": "Wflow", 
        "Severity": "S3", 
        "SrAge": 7, 
        "SrNumber": "07966141", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|7.3.1-125|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "gsan", 
        "CustLoc": "NA", 
        "CustomerName": "SOGESTION", 
        "Desc": "Avamar 7.3.1-125: MCS GUI shows popup \"Error \"tschedlog::tschedlog Failed to open persistent log (server_exception(MSG_ERR_NOT_PRESENT))\"", 
        "EnggLoc": "---", 
        "Esc": 29793, 
        "EscAge": 1, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-14", 
        "OtherAssignee": "", 
        "Owner": "Kerry Li", 
        "OwnerEmail": "Kerry.Li@emc.com", 
        "ProdName": "Srvr", 
        "Severity": "S3", 
        "SrAge": 6, 
        "SrNumber": "87836666", 
        "Team": "DEV", 
        "Versions": "[7.3.1-125|---|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "NDMP NetApp", 
        "CustLoc": "APJ", 
        "CustomerName": "eHealth NSW", 
        "Desc": "PR 9810: NC - NDMP Netapp - SR<#87831048> - <NDMP Restore to same NAS filter but different location. it failed with error avtar Error <8738>: Inode 889329 was supposed to be restored, but not found in backup >", 
        "EnggLoc": "---", 
        "Esc": 29799, 
        "EscAge": 1, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-08", 
        "OtherAssignee": "", 
        "Owner": "Jerry Jie", 
        "OwnerEmail": "jerry.jie@emc.com", 
        "ProdName": "clnts", 
        "Severity": "S1", 
        "SrAge": 6, 
        "SrNumber": "87831048", 
        "Team": "SPT", 
        "Versions": "[7.2.1-32|7.2.1-32|7.2.101-32]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }, 
    {
        "Cmnt": 0, 
        "CompName": "MCS - backup user mgmt", 
        "CustLoc": "EMEA", 
        "CustomerName": "Veolia DataCenter Podstawowe", 
        "Desc": "Request to port fix to v7.1.2-21 for Restore Operator user privileges problem | BUG-280021", 
        "EnggLoc": "---", 
        "Esc": 29800, 
        "EscAge": 1, 
        "Mod": 0, 
        "NextUpdateActionPlan": "", 
        "NextUpdateDate": "08-14", 
        "OtherAssignee": "", 
        "Owner": "MC Team alias", 
        "OwnerEmail": "mc@avamar.com", 
        "ProdName": "MCS", 
        "Severity": "S3", 
        "SrAge": 6, 
        "SrNumber": "08153765", 
        "Team": "DEV", 
        "Versions": "[---|7.1.2-21|---]", 
        "WhiteBoard": "", 
        "empty": "empty"
    }

];
